package com.atalaya.sonido;

import com.atalaya.Atalaya;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.sounds.SoundEvent;

/**
 * Sonidos propios del mod.
 *
 * Ninguno es de vanilla: los .ogg salen de scripts de sintesis que construyen
 * cada uno con lo que el bicho tiene encima. Los del Vigia, con el hierro del
 * farol, el cristal, las cadenas, una garganta y la llama; los de Nerea
 * (nerea_sonidos.py), con agua, piedra, hueso, cadenas y una voz sumergida; los de
 * Aeralis (aeralis_sonidos.py), con viento, alas, quitina, tornados y truenos.
 *
 * Aqui solo se registra el NOMBRE de cada evento. Que fichero suena, con que
 * variantes y con que subtitulo lo dice assets/atalaya/sounds.json.
 */
public final class AtalayaSonidos {

    public static SoundEvent VIGIA_AMBIENTE;
    public static SoundEvent VIGIA_ACECHO;
    public static SoundEvent VIGIA_PASO;
    public static SoundEvent VIGIA_HERIDO;
    public static SoundEvent VIGIA_MUERTE;
    public static SoundEvent VIGIA_APAGARSE;
    public static SoundEvent VIGIA_FAROL_CAE;
    public static SoundEvent VIGIA_ALERTA;
    public static SoundEvent VIGIA_CEPO_ABRIR;
    public static SoundEvent VIGIA_CEPO_CERRAR;
    public static SoundEvent VIGIA_CEPO_FALLO;
    public static SoundEvent VIGIA_MIRADA_CARGA;
    public static SoundEvent VIGIA_MIRADA_DISPARO;
    public static SoundEvent VIGIA_MIRADA_CORTE;
    public static SoundEvent VIGIA_RAYO_VUELO;
    public static SoundEvent VIGIA_RAYO_IMPACTO;
    public static SoundEvent VIGIA_TAMBALEO;
    public static SoundEvent VIGIA_BUSCAR;
    public static SoundEvent OJO_VIGIA_USAR;

    // --- Nerea: agua, piedra, hueso, cadenas y una voz bajo el agua ---
    public static SoundEvent NEREA_AMBIENTE;
    public static SoundEvent NEREA_PASO;
    public static SoundEvent NEREA_INMUNE;
    public static SoundEvent NEREA_HERIDO;
    public static SoundEvent NEREA_RUGIDO;
    public static SoundEvent NEREA_DESPERTAR;
    public static SoundEvent NEREA_ROMPEOLAS_ALZAR;
    public static SoundEvent NEREA_ROMPEOLAS_GOLPE;
    public static SoundEvent NEREA_OLA;
    public static SoundEvent NEREA_REMOLINO_AVISO;
    public static SoundEvent NEREA_REMOLINO;
    public static SoundEvent NEREA_ANTORCHA;
    public static SoundEvent NEREA_BURBUJAS;
    public static SoundEvent NEREA_BURBUJA_REVIENTA;
    public static SoundEvent NEREA_BURBUJA_POMPA;
    public static SoundEvent NEREA_MOLINO_ARRASTRE;
    public static SoundEvent NEREA_MOLINO_GIRO;
    public static SoundEvent NEREA_ARPON_LANZAR;
    public static SoundEvent NEREA_ARPON_ENGANCHA;
    public static SoundEvent NEREA_ARPON_REBOTA;
    public static SoundEvent NEREA_ESTOCADA;
    public static SoundEvent NEREA_MIRADA_CARGA;
    public static SoundEvent NEREA_MIRADA_RAYO;
    public static SoundEvent NEREA_MIRADA_IMPACTO;
    public static SoundEvent NEREA_OJO_ROTO;
    public static SoundEvent NEREA_ATURDIDO;
    public static SoundEvent NEREA_SELLO_GOLPE;
    public static SoundEvent NEREA_SELLO_ROTO;
    public static SoundEvent NEREA_CADENA_ROMPE;
    public static SoundEvent NEREA_TAMBALEO;
    public static SoundEvent NEREA_AGOTADO;
    public static SoundEvent NEREA_LATIDO;
    public static SoundEvent NEREA_LIBERACION;
    public static SoundEvent NEREA_DISOLVER;
    // El remake de octubre de 2026: el Geiser del Abismo, la Gran Marea y la Furia.
    public static SoundEvent NEREA_GEISER_AVISO;
    public static SoundEvent NEREA_GEISER;
    public static SoundEvent NEREA_MAREA_ALZA;
    public static SoundEvent NEREA_MAREA;
    // Las mecanicas cooperativas de Nerea (octubre de 2026): nerea_cooperativas_sonidos.py
    public static SoundEvent NEREA_CANTO;
    public static SoundEvent NEREA_TRANCE;
    public static SoundEvent NEREA_TRANCE_CLIC;
    public static SoundEvent NEREA_DESPIERTA;
    public static SoundEvent NEREA_ENCADENAR;
    public static SoundEvent NEREA_CADENA_TIRON;
    public static SoundEvent NEREA_REFUGIO;
    public static SoundEvent NEREA_CUENTA;
    public static SoundEvent NEREA_MAREA_ALTA;
    public static SoundEvent NEREA_FURIA;
    // Los minijuegos de Nerea (octubre de 2026): nerea_minijuegos_sonidos.py. Nada de sonidos de Minecraft.
    public static SoundEvent NEREA_PESCA_LANZAR;
    public static SoundEvent NEREA_PESCA_CAE;
    public static SoundEvent NEREA_PESCA_PICA;
    public static SoundEvent NEREA_PESCA_RECOGER;
    public static SoundEvent NEREA_PESCA_ESCAPA;
    public static SoundEvent NEREA_PERLA_PESCADA;
    public static SoundEvent NEREA_PERLA_LANZAR;
    public static SoundEvent NEREA_PERLA_CORAZON;
    public static SoundEvent NEREA_MORENA_SALE;
    public static SoundEvent NEREA_MORENA_AVISO;
    public static SoundEvent NEREA_MORENA_MORDISCO;
    public static SoundEvent NEREA_MORENA_GOLPE;
    public static SoundEvent NEREA_MORENA_BAJA;
    public static SoundEvent NEREA_CANON_SALE;
    public static SoundEvent NEREA_BALA_COGER;
    public static SoundEvent NEREA_CANON_CARGAR;
    public static SoundEvent NEREA_CANON_VACIO;
    public static SoundEvent NEREA_CANON_DISPARO;
    public static SoundEvent NEREA_BALA_IMPACTO;
    public static SoundEvent NEREA_BALA_CAE;
    public static SoundEvent NEREA_DUELO_NOTA1;
    public static SoundEvent NEREA_DUELO_NOTA2;
    public static SoundEvent NEREA_DUELO_NOTA3;
    public static SoundEvent NEREA_DUELO_NOTA4;
    public static SoundEvent NEREA_DUELO_FALLO;
    public static SoundEvent NEREA_DUELO_PERFECTO;
    public static SoundEvent NEREA_DUELO_CUENTA;
    public static SoundEvent NEREA_DUELO_GANA;
    public static SoundEvent NEREA_DUELO_PIERDE;
    // La musica de cada jefe mientras pelea (musica_jefes.py; la pone MusicaJefes en el cliente).
    public static SoundEvent MUSICA_NEREA;
    public static SoundEvent MUSICA_AERALIS;
    public static SoundEvent MUSICA_RAJANG;
    public static SoundEvent MUSICA_NOVILIS;
    // El clink de las espadas de los jefes al golpear (armaduras_sonidos.py).
    public static SoundEvent ESPADA_MAREAS_GOLPE;
    public static SoundEvent ESPADA_JADE_GOLPE;
    public static SoundEvent ESPADA_VENDAVAL_GOLPE;
    // Las armaduras de rol: las activas, el aviso de lista y las armas.
    public static SoundEvent HABILIDAD_MURALLA;
    public static SoundEvent HABILIDAD_MANANTIAL;
    public static SoundEvent HABILIDAD_MANANTIAL_PULSO;
    public static SoundEvent HABILIDAD_CORRIENTE;
    public static SoundEvent HABILIDAD_FURIA;
    public static SoundEvent HABILIDAD_LISTA;
    public static SoundEvent MARTILLO_GOLPE;
    public static SoundEvent MARTILLO_CARGA;
    public static SoundEvent TRIDENTE_LANZAR;
    public static SoundEvent TRIDENTE_VUELVE;
    public static SoundEvent TRIDENTE_CURA;
    public static SoundEvent MAREAS_TRIDENTE_GOLPE;
    public static SoundEvent ARCO_DISPARO;
    public static SoundEvent FLECHA_ALIADO;
    public static SoundEvent ESPADA_SOLAR_GOLPE;
    // Los acentos de cada pista: los golpes gordos, la Furia (y los grandes momentos) y el cambio de fase.
    public static SoundEvent MUSICA_NEREA_GOLPE;
    public static SoundEvent MUSICA_NEREA_GRANDE;
    public static SoundEvent MUSICA_NEREA_FASE;
    public static SoundEvent MUSICA_AERALIS_GOLPE;
    public static SoundEvent MUSICA_AERALIS_GRANDE;
    public static SoundEvent MUSICA_AERALIS_FASE;
    public static SoundEvent MUSICA_RAJANG_GOLPE;
    public static SoundEvent MUSICA_RAJANG_GRANDE;
    public static SoundEvent MUSICA_RAJANG_FASE;
    public static SoundEvent MUSICA_NOVILIS_GOLPE;
    public static SoundEvent MUSICA_NOVILIS_GRANDE;
    public static SoundEvent MUSICA_NOVILIS_FASE;

    public static SoundEvent AERALIS_AMBIENTE;
    public static SoundEvent AERALIS_ALETEO;
    public static SoundEvent AERALIS_INMUNE;
    public static SoundEvent AERALIS_HERIDO;
    public static SoundEvent AERALIS_CHILLIDO;
    public static SoundEvent AERALIS_DESPERTAR;
    public static SoundEvent AERALIS_ALETEO_CARGA;
    public static SoundEvent AERALIS_ALETEO_CORTE;
    public static SoundEvent AERALIS_CUCHILLA_GOLPE;
    public static SoundEvent AERALIS_TORNADOS_GOLPE;
    public static SoundEvent AERALIS_TORNADO_NACE;
    public static SoundEvent AERALIS_TORNADO;
    public static SoundEvent AERALIS_TORNADO_ATRAPA;
    public static SoundEvent AERALIS_TORNADO_EXPLOTA;
    public static SoundEvent AERALIS_TORNADO_ROMPE;
    public static SoundEvent AERALIS_MARCA;
    public static SoundEvent AERALIS_RAFAGA;
    public static SoundEvent AERALIS_RAFAGA_ROMPE;
    public static SoundEvent AERALIS_RAFAGA_GOLPE;
    public static SoundEvent AERALIS_JUICIO_SILENCIO;
    public static SoundEvent AERALIS_JUICIO_CIRCULO;
    public static SoundEvent AERALIS_JUICIO_CICLON;
    public static SoundEvent AERALIS_NUCLEO;
    public static SoundEvent AERALIS_NUCLEO_GOLPE;
    public static SoundEvent AERALIS_NUCLEO_ROTO;
    public static SoundEvent AERALIS_JUICIO_GOLPE;
    public static SoundEvent AERALIS_TRUENO;
    public static SoundEvent AERALIS_TAMBALEO;
    public static SoundEvent AERALIS_ATURDIDA;
    public static SoundEvent AERALIS_AGOTADA;
    public static SoundEvent AERALIS_JADEO;
    public static SoundEvent AERALIS_LIBERACION;
    public static SoundEvent AERALIS_DISOLVER;
    // El remake de octubre de 2026 (aeralis_mejoras_sonidos.py)
    public static SoundEvent AERALIS_PICADO_AVISO;
    public static SoundEvent AERALIS_PICADO;
    public static SoundEvent AERALIS_POSADA;
    public static SoundEvent AERALIS_ESCAMAS;
    public static SoundEvent AERALIS_ESCAMAS_DESCARGA;
    public static SoundEvent AERALIS_VIENTO_VUELTA;

    // Rajang, el Jaguar de Jade (rajang_sonidos.py)
    public static SoundEvent RAJANG_AMBIENTE;
    public static SoundEvent RAJANG_DORMIDO;
    public static SoundEvent RAJANG_PASO;
    public static SoundEvent RAJANG_HERIDO;
    public static SoundEvent RAJANG_INMUNE;
    public static SoundEvent RAJANG_DESPERTAR;
    public static SoundEvent RAJANG_RUGIDO;
    public static SoundEvent RAJANG_GRUNIDO;
    public static SoundEvent RAJANG_ZARPAZO;
    public static SoundEvent RAJANG_GARRA_ALZA;
    public static SoundEvent RAJANG_GARRA_GOLPE;
    public static SoundEvent RAJANG_GRIETA;
    public static SoundEvent RAJANG_PICO;
    public static SoundEvent RAJANG_PICO_GOLPE;
    public static SoundEvent RAJANG_TERREMOTO;
    public static SoundEvent RAJANG_ONDA;
    public static SoundEvent RAJANG_PILAR;
    public static SoundEvent RAJANG_AVISO;
    public static SoundEvent RAJANG_PIEL_JADE;
    public static SoundEvent RAJANG_LASTRE;
    public static SoundEvent RAJANG_SELLO;
    public static SoundEvent RAJANG_PLATAFORMA;
    public static SoundEvent RAJANG_TOTEM;
    public static SoundEvent RAJANG_TOTEM_GOLPE;
    public static SoundEvent RAJANG_TOTEM_ROTO;
    public static SoundEvent RAJANG_TOTEM_REHACE;
    public static SoundEvent RAJANG_COLUMNA;
    public static SoundEvent RAJANG_RUGIDO_JADE;
    public static SoundEvent RAJANG_RELOJ;
    public static SoundEvent RAJANG_CATACLISMO;
    public static SoundEvent RAJANG_CIELO;
    public static SoundEvent RAJANG_FRAGMENTO;
    public static SoundEvent RAJANG_IMPACTO;
    public static SoundEvent RAJANG_MARCA;
    public static SoundEvent RAJANG_SALTO;
    public static SoundEvent RAJANG_ATERRIZA;
    public static SoundEvent RAJANG_ATURDIDO;
    public static SoundEvent RAJANG_PARALIZADO;
    public static SoundEvent RAJANG_CURA;
    public static SoundEvent RAJANG_TAMBALEO;
    public static SoundEvent RAJANG_LIBERACION;
    public static SoundEvent RAJANG_DISOLVER;
    // Las mejoras de octubre de 2026 (al final de rajang_sonidos.py, con su propia semilla)
    public static SoundEvent RAJANG_EMBESTIDA_AVISO;
    public static SoundEvent RAJANG_EMBESTIDA;
    public static SoundEvent RAJANG_EMBESTIDA_FRENA;
    public static SoundEvent RAJANG_ESTAMPADO;
    public static SoundEvent RAJANG_TUMBA;
    public static SoundEvent RAJANG_TUMBA_ESTALLA;
    public static SoundEvent RAJANG_FURIA;
    public static SoundEvent RAJANG_ESCALON_TIEMBLA;
    public static SoundEvent RAJANG_ESCALON_CAE;
    public static SoundEvent RAJANG_TOTEM_PULSO;

    // Novilis, el Caballero Solar (novilis_sonidos.py): fuego, lava, acero, su sol y
    // una voz por el yelmo. Las cuatro melodias son las voces de las trompetas de las
    // estatuas, de la misma duracion exacta (24 s), en streaming.
    public static SoundEvent NOVILIS_DESPERTAR;
    public static SoundEvent NOVILIS_PASO;
    public static SoundEvent NOVILIS_AMBIENTE;
    public static SoundEvent NOVILIS_HERIDO;
    public static SoundEvent NOVILIS_RUGIDO;
    public static SoundEvent NOVILIS_TAJO;
    public static SoundEvent NOVILIS_TAJO_FUEGO;
    public static SoundEvent NOVILIS_CASTIGO_ALZA;
    public static SoundEvent NOVILIS_CASTIGO_AVISO;
    public static SoundEvent NOVILIS_CASTIGO_RAYO;
    public static SoundEvent NOVILIS_CASTIGO_CLAVA;
    public static SoundEvent NOVILIS_ONDA;
    public static SoundEvent NOVILIS_SOL_FORMA;
    public static SoundEvent NOVILIS_SOL_LANZA;
    public static SoundEvent NOVILIS_SOL_EXPLOTA;
    public static SoundEvent NOVILIS_LAVA;
    public static SoundEvent NOVILIS_ESTATUAS;
    public static SoundEvent NOVILIS_MELODIA_1;
    public static SoundEvent NOVILIS_MELODIA_2;
    public static SoundEvent NOVILIS_MELODIA_3;
    public static SoundEvent NOVILIS_MELODIA_4;
    public static SoundEvent NOVILIS_ESTATUA_GOLPE;
    public static SoundEvent NOVILIS_ESTATUA_ROTA;
    public static SoundEvent NOVILIS_CARGA;
    public static SoundEvent NOVILIS_SUPERNOVA;
    public static SoundEvent NOVILIS_SOL_APAGA;
    public static SoundEvent NOVILIS_OFRENDA_MARCA;
    public static SoundEvent NOVILIS_OFRENDA_AGARRA;
    public static SoundEvent NOVILIS_OFRENDA_TECLA;
    public static SoundEvent NOVILIS_OFRENDA_FALLO;
    public static SoundEvent NOVILIS_OFRENDA_LIBRE;
    public static SoundEvent NOVILIS_DIOS;
    public static SoundEvent NOVILIS_DIOS_AVISO;
    public static SoundEvent NOVILIS_DIOS_EXPLOSION;
    public static SoundEvent NOVILIS_GRITO;
    public static SoundEvent NOVILIS_FURIA;
    public static SoundEvent NOVILIS_ATURDIDO;
    public static SoundEvent NOVILIS_TAMBALEO;
    public static SoundEvent NOVILIS_INMUNE;
    public static SoundEvent NOVILIS_LIBERACION;
    public static SoundEvent NOVILIS_DISOLVER;
    // Los ataques de octubre (08-10-2026)
    public static SoundEvent NOVILIS_EMBESTIDA;
    public static SoundEvent NOVILIS_CAMINO;
    public static SoundEvent NOVILIS_INFERNAL_SALTO;
    public static SoundEvent NOVILIS_INFERNAL_GOLPE;
    public static SoundEvent NOVILIS_GRIETA;
    public static SoundEvent NOVILIS_GEISER;
    public static SoundEvent NOVILIS_INFERNAL_EXPLOTA;
    public static SoundEvent NOVILIS_MAR;

    private AtalayaSonidos() {
    }

    public static void registrar() {
        VIGIA_AMBIENTE = registrar("vigia.ambiente");
        VIGIA_ACECHO = registrar("vigia.acecho");
        VIGIA_PASO = registrar("vigia.paso");
        VIGIA_HERIDO = registrar("vigia.herido");
        VIGIA_MUERTE = registrar("vigia.muerte");
        VIGIA_APAGARSE = registrar("vigia.apagarse");
        VIGIA_FAROL_CAE = registrar("vigia.farol_cae");
        VIGIA_ALERTA = registrar("vigia.alerta");
        VIGIA_CEPO_ABRIR = registrar("vigia.cepo_abrir");
        VIGIA_CEPO_CERRAR = registrar("vigia.cepo_cerrar");
        VIGIA_CEPO_FALLO = registrar("vigia.cepo_fallo");
        VIGIA_MIRADA_CARGA = registrar("vigia.mirada_carga");
        VIGIA_MIRADA_DISPARO = registrar("vigia.mirada_disparo");
        VIGIA_MIRADA_CORTE = registrar("vigia.mirada_corte");
        VIGIA_RAYO_VUELO = registrar("vigia.rayo_vuelo");
        VIGIA_RAYO_IMPACTO = registrar("vigia.rayo_impacto");
        VIGIA_TAMBALEO = registrar("vigia.tambaleo");
        VIGIA_BUSCAR = registrar("vigia.buscar");
        OJO_VIGIA_USAR = registrar("ojo_vigia.usar");

        NEREA_AMBIENTE = registrar("nerea.ambiente");
        NEREA_PASO = registrar("nerea.paso");
        NEREA_INMUNE = registrar("nerea.inmune");
        NEREA_HERIDO = registrar("nerea.herido");
        NEREA_RUGIDO = registrar("nerea.rugido");
        NEREA_DESPERTAR = registrar("nerea.despertar");
        NEREA_ROMPEOLAS_ALZAR = registrar("nerea.rompeolas_alzar");
        NEREA_ROMPEOLAS_GOLPE = registrar("nerea.rompeolas_golpe");
        NEREA_OLA = registrar("nerea.ola");
        NEREA_REMOLINO_AVISO = registrar("nerea.remolino_aviso");
        NEREA_REMOLINO = registrar("nerea.remolino");
        NEREA_ANTORCHA = registrar("nerea.antorcha");
        NEREA_BURBUJAS = registrar("nerea.burbujas");
        NEREA_BURBUJA_REVIENTA = registrar("nerea.burbuja_revienta");
        NEREA_BURBUJA_POMPA = registrar("nerea.burbuja_pompa");
        NEREA_MOLINO_ARRASTRE = registrar("nerea.molino_arrastre");
        NEREA_MOLINO_GIRO = registrar("nerea.molino_giro");
        NEREA_ARPON_LANZAR = registrar("nerea.arpon_lanzar");
        NEREA_ARPON_ENGANCHA = registrar("nerea.arpon_engancha");
        NEREA_ARPON_REBOTA = registrar("nerea.arpon_rebota");
        NEREA_ESTOCADA = registrar("nerea.estocada");
        NEREA_MIRADA_CARGA = registrar("nerea.mirada_carga");
        NEREA_MIRADA_RAYO = registrar("nerea.mirada_rayo");
        NEREA_MIRADA_IMPACTO = registrar("nerea.mirada_impacto");
        NEREA_OJO_ROTO = registrar("nerea.ojo_roto");
        NEREA_ATURDIDO = registrar("nerea.aturdido");
        NEREA_SELLO_GOLPE = registrar("nerea.sello_golpe");
        NEREA_SELLO_ROTO = registrar("nerea.sello_roto");
        NEREA_CADENA_ROMPE = registrar("nerea.cadena_rompe");
        NEREA_TAMBALEO = registrar("nerea.tambaleo");
        NEREA_AGOTADO = registrar("nerea.agotado");
        NEREA_LATIDO = registrar("nerea.latido");
        NEREA_LIBERACION = registrar("nerea.liberacion");
        NEREA_DISOLVER = registrar("nerea.disolver");
        NEREA_GEISER_AVISO = registrar("nerea.geiser_aviso");
        NEREA_GEISER = registrar("nerea.geiser");
        NEREA_MAREA_ALZA = registrar("nerea.marea_alza");
        NEREA_MAREA = registrar("nerea.marea");
        NEREA_CANTO = registrar("nerea.canto");
        NEREA_TRANCE = registrar("nerea.trance");
        NEREA_TRANCE_CLIC = registrar("nerea.trance_clic");
        NEREA_DESPIERTA = registrar("nerea.despierta");
        NEREA_ENCADENAR = registrar("nerea.encadenar");
        NEREA_CADENA_TIRON = registrar("nerea.cadena_tiron");
        NEREA_REFUGIO = registrar("nerea.refugio");
        NEREA_CUENTA = registrar("nerea.cuenta");
        NEREA_MAREA_ALTA = registrar("nerea.marea_alta");
        NEREA_FURIA = registrar("nerea.furia");
        NEREA_PESCA_LANZAR = registrar("nerea.pesca_lanzar");
        NEREA_PESCA_CAE = registrar("nerea.pesca_cae");
        NEREA_PESCA_PICA = registrar("nerea.pesca_pica");
        NEREA_PESCA_RECOGER = registrar("nerea.pesca_recoger");
        NEREA_PESCA_ESCAPA = registrar("nerea.pesca_escapa");
        NEREA_PERLA_PESCADA = registrar("nerea.perla_pescada");
        NEREA_PERLA_LANZAR = registrar("nerea.perla_lanzar");
        NEREA_PERLA_CORAZON = registrar("nerea.perla_corazon");
        NEREA_MORENA_SALE = registrar("nerea.morena_sale");
        NEREA_MORENA_AVISO = registrar("nerea.morena_aviso");
        NEREA_MORENA_MORDISCO = registrar("nerea.morena_mordisco");
        NEREA_MORENA_GOLPE = registrar("nerea.morena_golpe");
        NEREA_MORENA_BAJA = registrar("nerea.morena_baja");
        NEREA_CANON_SALE = registrar("nerea.canon_sale");
        NEREA_BALA_COGER = registrar("nerea.bala_coger");
        NEREA_CANON_CARGAR = registrar("nerea.canon_cargar");
        NEREA_CANON_VACIO = registrar("nerea.canon_vacio");
        NEREA_CANON_DISPARO = registrar("nerea.canon_disparo");
        NEREA_BALA_IMPACTO = registrar("nerea.bala_impacto");
        NEREA_BALA_CAE = registrar("nerea.bala_cae");
        NEREA_DUELO_NOTA1 = registrar("nerea.duelo_nota1");
        NEREA_DUELO_NOTA2 = registrar("nerea.duelo_nota2");
        NEREA_DUELO_NOTA3 = registrar("nerea.duelo_nota3");
        NEREA_DUELO_NOTA4 = registrar("nerea.duelo_nota4");
        NEREA_DUELO_FALLO = registrar("nerea.duelo_fallo");
        NEREA_DUELO_PERFECTO = registrar("nerea.duelo_perfecto");
        NEREA_DUELO_CUENTA = registrar("nerea.duelo_cuenta");
        NEREA_DUELO_GANA = registrar("nerea.duelo_gana");
        NEREA_DUELO_PIERDE = registrar("nerea.duelo_pierde");
        MUSICA_NEREA = registrar("musica.nerea");
        MUSICA_AERALIS = registrar("musica.aeralis");
        MUSICA_RAJANG = registrar("musica.rajang");
        MUSICA_NOVILIS = registrar("musica.novilis");
        ESPADA_MAREAS_GOLPE = registrar("espada.mareas_golpe");
        ESPADA_JADE_GOLPE = registrar("espada.jade_golpe");
        ESPADA_VENDAVAL_GOLPE = registrar("espada.vendaval_golpe");
        HABILIDAD_MURALLA = registrar("habilidad.muralla");
        HABILIDAD_MANANTIAL = registrar("habilidad.manantial");
        HABILIDAD_MANANTIAL_PULSO = registrar("habilidad.manantial_pulso");
        HABILIDAD_CORRIENTE = registrar("habilidad.corriente");
        HABILIDAD_FURIA = registrar("habilidad.furia");
        HABILIDAD_LISTA = registrar("habilidad.lista");
        MARTILLO_GOLPE = registrar("arma.martillo_golpe");
        MARTILLO_CARGA = registrar("arma.martillo_carga");
        TRIDENTE_LANZAR = registrar("arma.tridente_lanzar");
        TRIDENTE_VUELVE = registrar("arma.tridente_vuelve");
        TRIDENTE_CURA = registrar("arma.tridente_cura");
        MAREAS_TRIDENTE_GOLPE = registrar("arma.tridente_golpe");
        ARCO_DISPARO = registrar("arma.arco_disparo");
        FLECHA_ALIADO = registrar("arma.flecha_aliado");
        ESPADA_SOLAR_GOLPE = registrar("espada.solar_golpe");
        MUSICA_NEREA_GOLPE = registrar("musica.nerea.golpe");
        MUSICA_NEREA_GRANDE = registrar("musica.nerea.grande");
        MUSICA_NEREA_FASE = registrar("musica.nerea.fase");
        MUSICA_AERALIS_GOLPE = registrar("musica.aeralis.golpe");
        MUSICA_AERALIS_GRANDE = registrar("musica.aeralis.grande");
        MUSICA_AERALIS_FASE = registrar("musica.aeralis.fase");
        MUSICA_RAJANG_GOLPE = registrar("musica.rajang.golpe");
        MUSICA_RAJANG_GRANDE = registrar("musica.rajang.grande");
        MUSICA_RAJANG_FASE = registrar("musica.rajang.fase");
        MUSICA_NOVILIS_GOLPE = registrar("musica.novilis.golpe");
        MUSICA_NOVILIS_GRANDE = registrar("musica.novilis.grande");
        MUSICA_NOVILIS_FASE = registrar("musica.novilis.fase");

        AERALIS_AMBIENTE = registrar("aeralis.ambiente");
        AERALIS_ALETEO = registrar("aeralis.aleteo");
        AERALIS_INMUNE = registrar("aeralis.inmune");
        AERALIS_HERIDO = registrar("aeralis.herido");
        AERALIS_CHILLIDO = registrar("aeralis.chillido");
        AERALIS_DESPERTAR = registrar("aeralis.despertar");
        AERALIS_ALETEO_CARGA = registrar("aeralis.aleteo_carga");
        AERALIS_ALETEO_CORTE = registrar("aeralis.aleteo_corte");
        AERALIS_CUCHILLA_GOLPE = registrar("aeralis.cuchilla_golpe");
        AERALIS_TORNADOS_GOLPE = registrar("aeralis.tornados_golpe");
        AERALIS_TORNADO_NACE = registrar("aeralis.tornado_nace");
        AERALIS_TORNADO = registrar("aeralis.tornado");
        AERALIS_TORNADO_ATRAPA = registrar("aeralis.tornado_atrapa");
        AERALIS_TORNADO_EXPLOTA = registrar("aeralis.tornado_explota");
        AERALIS_TORNADO_ROMPE = registrar("aeralis.tornado_rompe");
        AERALIS_MARCA = registrar("aeralis.marca");
        AERALIS_RAFAGA = registrar("aeralis.rafaga");
        AERALIS_RAFAGA_ROMPE = registrar("aeralis.rafaga_rompe");
        AERALIS_RAFAGA_GOLPE = registrar("aeralis.rafaga_golpe");
        AERALIS_JUICIO_SILENCIO = registrar("aeralis.juicio_silencio");
        AERALIS_JUICIO_CIRCULO = registrar("aeralis.juicio_circulo");
        AERALIS_JUICIO_CICLON = registrar("aeralis.juicio_ciclon");
        AERALIS_NUCLEO = registrar("aeralis.nucleo");
        AERALIS_NUCLEO_GOLPE = registrar("aeralis.nucleo_golpe");
        AERALIS_NUCLEO_ROTO = registrar("aeralis.nucleo_roto");
        AERALIS_JUICIO_GOLPE = registrar("aeralis.juicio_golpe");
        AERALIS_TRUENO = registrar("aeralis.trueno");
        AERALIS_TAMBALEO = registrar("aeralis.tambaleo");
        AERALIS_ATURDIDA = registrar("aeralis.aturdida");
        AERALIS_AGOTADA = registrar("aeralis.agotada");
        AERALIS_JADEO = registrar("aeralis.jadeo");
        AERALIS_LIBERACION = registrar("aeralis.liberacion");
        AERALIS_DISOLVER = registrar("aeralis.disolver");
        AERALIS_PICADO_AVISO = registrar("aeralis.picado_aviso");
        AERALIS_PICADO = registrar("aeralis.picado");
        AERALIS_POSADA = registrar("aeralis.posada");
        AERALIS_ESCAMAS = registrar("aeralis.escamas");
        AERALIS_ESCAMAS_DESCARGA = registrar("aeralis.escamas_descarga");
        AERALIS_VIENTO_VUELTA = registrar("aeralis.viento_vuelta");
        RAJANG_AMBIENTE = registrar("rajang.ambiente");
        RAJANG_DORMIDO = registrar("rajang.dormido");
        RAJANG_PASO = registrar("rajang.paso");
        RAJANG_HERIDO = registrar("rajang.herido");
        RAJANG_INMUNE = registrar("rajang.inmune");
        RAJANG_DESPERTAR = registrar("rajang.despertar");
        RAJANG_RUGIDO = registrar("rajang.rugido");
        RAJANG_GRUNIDO = registrar("rajang.grunido");
        RAJANG_ZARPAZO = registrar("rajang.zarpazo");
        RAJANG_GARRA_ALZA = registrar("rajang.garra_alza");
        RAJANG_GARRA_GOLPE = registrar("rajang.garra_golpe");
        RAJANG_GRIETA = registrar("rajang.grieta");
        RAJANG_PICO = registrar("rajang.pico");
        RAJANG_PICO_GOLPE = registrar("rajang.pico_golpe");
        RAJANG_TERREMOTO = registrar("rajang.terremoto");
        RAJANG_ONDA = registrar("rajang.onda");
        RAJANG_PILAR = registrar("rajang.pilar");
        RAJANG_AVISO = registrar("rajang.aviso");
        RAJANG_PIEL_JADE = registrar("rajang.piel_jade");
        RAJANG_LASTRE = registrar("rajang.lastre");
        RAJANG_SELLO = registrar("rajang.sello");
        RAJANG_PLATAFORMA = registrar("rajang.plataforma");
        RAJANG_TOTEM = registrar("rajang.totem");
        RAJANG_TOTEM_GOLPE = registrar("rajang.totem_golpe");
        RAJANG_TOTEM_ROTO = registrar("rajang.totem_roto");
        RAJANG_TOTEM_REHACE = registrar("rajang.totem_rehace");
        RAJANG_COLUMNA = registrar("rajang.columna");
        RAJANG_RUGIDO_JADE = registrar("rajang.rugido_jade");
        RAJANG_RELOJ = registrar("rajang.reloj");
        RAJANG_CATACLISMO = registrar("rajang.cataclismo");
        RAJANG_CIELO = registrar("rajang.cielo");
        RAJANG_FRAGMENTO = registrar("rajang.fragmento");
        RAJANG_IMPACTO = registrar("rajang.impacto");
        RAJANG_MARCA = registrar("rajang.marca");
        RAJANG_SALTO = registrar("rajang.salto");
        RAJANG_ATERRIZA = registrar("rajang.aterriza");
        RAJANG_ATURDIDO = registrar("rajang.aturdido");
        RAJANG_PARALIZADO = registrar("rajang.paralizado");
        RAJANG_CURA = registrar("rajang.cura");
        RAJANG_TAMBALEO = registrar("rajang.tambaleo");
        RAJANG_LIBERACION = registrar("rajang.liberacion");
        RAJANG_DISOLVER = registrar("rajang.disolver");
        RAJANG_EMBESTIDA_AVISO = registrar("rajang.embestida_aviso");
        RAJANG_EMBESTIDA = registrar("rajang.embestida");
        RAJANG_EMBESTIDA_FRENA = registrar("rajang.embestida_frena");
        RAJANG_ESTAMPADO = registrar("rajang.estampado");
        RAJANG_TUMBA = registrar("rajang.tumba");
        RAJANG_TUMBA_ESTALLA = registrar("rajang.tumba_estalla");
        RAJANG_FURIA = registrar("rajang.furia");
        RAJANG_ESCALON_TIEMBLA = registrar("rajang.escalon_tiembla");
        RAJANG_ESCALON_CAE = registrar("rajang.escalon_cae");
        RAJANG_TOTEM_PULSO = registrar("rajang.totem_pulso");
        NOVILIS_DESPERTAR = registrar("novilis.despertar");
        NOVILIS_PASO = registrar("novilis.paso");
        NOVILIS_AMBIENTE = registrar("novilis.ambiente");
        NOVILIS_HERIDO = registrar("novilis.herido");
        NOVILIS_RUGIDO = registrar("novilis.rugido");
        NOVILIS_TAJO = registrar("novilis.tajo");
        NOVILIS_TAJO_FUEGO = registrar("novilis.tajo_fuego");
        NOVILIS_CASTIGO_ALZA = registrar("novilis.castigo_alza");
        NOVILIS_CASTIGO_AVISO = registrar("novilis.castigo_aviso");
        NOVILIS_CASTIGO_RAYO = registrar("novilis.castigo_rayo");
        NOVILIS_CASTIGO_CLAVA = registrar("novilis.castigo_clava");
        NOVILIS_ONDA = registrar("novilis.onda");
        NOVILIS_SOL_FORMA = registrar("novilis.sol_forma");
        NOVILIS_SOL_LANZA = registrar("novilis.sol_lanza");
        NOVILIS_SOL_EXPLOTA = registrar("novilis.sol_explota");
        NOVILIS_LAVA = registrar("novilis.lava");
        NOVILIS_ESTATUAS = registrar("novilis.estatuas");
        NOVILIS_MELODIA_1 = registrar("novilis.melodia_1");
        NOVILIS_MELODIA_2 = registrar("novilis.melodia_2");
        NOVILIS_MELODIA_3 = registrar("novilis.melodia_3");
        NOVILIS_MELODIA_4 = registrar("novilis.melodia_4");
        NOVILIS_ESTATUA_GOLPE = registrar("novilis.estatua_golpe");
        NOVILIS_ESTATUA_ROTA = registrar("novilis.estatua_rota");
        NOVILIS_CARGA = registrar("novilis.carga");
        NOVILIS_SUPERNOVA = registrar("novilis.supernova");
        NOVILIS_SOL_APAGA = registrar("novilis.sol_apaga");
        NOVILIS_OFRENDA_MARCA = registrar("novilis.ofrenda_marca");
        NOVILIS_OFRENDA_AGARRA = registrar("novilis.ofrenda_agarra");
        NOVILIS_OFRENDA_TECLA = registrar("novilis.ofrenda_tecla");
        NOVILIS_OFRENDA_FALLO = registrar("novilis.ofrenda_fallo");
        NOVILIS_OFRENDA_LIBRE = registrar("novilis.ofrenda_libre");
        NOVILIS_DIOS = registrar("novilis.dios");
        NOVILIS_DIOS_AVISO = registrar("novilis.dios_aviso");
        NOVILIS_DIOS_EXPLOSION = registrar("novilis.dios_explosion");
        NOVILIS_GRITO = registrar("novilis.grito");
        NOVILIS_FURIA = registrar("novilis.furia");
        NOVILIS_ATURDIDO = registrar("novilis.aturdido");
        NOVILIS_TAMBALEO = registrar("novilis.tambaleo");
        NOVILIS_INMUNE = registrar("novilis.inmune");
        NOVILIS_LIBERACION = registrar("novilis.liberacion");
        NOVILIS_DISOLVER = registrar("novilis.disolver");
        NOVILIS_EMBESTIDA = registrar("novilis.embestida");
        NOVILIS_CAMINO = registrar("novilis.camino");
        NOVILIS_INFERNAL_SALTO = registrar("novilis.infernal_salto");
        NOVILIS_INFERNAL_GOLPE = registrar("novilis.infernal_golpe");
        NOVILIS_GRIETA = registrar("novilis.grieta");
        NOVILIS_GEISER = registrar("novilis.geiser");
        NOVILIS_INFERNAL_EXPLOTA = registrar("novilis.infernal_explota");
        NOVILIS_MAR = registrar("novilis.mar");
    }

    private static SoundEvent registrar(String nombre) {
        Identifier id = Identifier.fromNamespaceAndPath(Atalaya.MOD_ID, nombre);
        return Registry.register(BuiltInRegistries.SOUND_EVENT, id, SoundEvent.createVariableRangeEvent(id));
    }
}
